### ISSUE TITLE
Is it fully ported to py3/Qt5 ?

### ISSUE THREAD

**Issue by luzpaz** [MariwanJ/nurbs#1]
I'm asking since maybe we can replace this repo with microelly2's which is what the current addon manager points to.

**Comment by MariwanJ** [comment]
no. 
He has a custom designed translation of a layout he creates for creating QT GUI. It is hard to understand. 
So, any command has QT GUI , I couldn't fix yet. and As it is mentioned at the github for nurbs, I will not put more effort on it. People at freecad forum are discourage you totally. You feel stupid that you put your effort to help other users. Sure not all are so. 
I have several technical questions at the forum, no one answer.. As soon as I talk about something which might be negative against a kinda work some one else did .. I face many commenters replying.
So where are you all when I ask technical questions?
No one helped me in my effort .. no one care .. 
So, why should I do it?
I will avoid writing anything at the form. This is not the first time I face it. 
If you wish to take back the code, it is up to you ... but it needs some more effort. At the moment I don't have any more energy to do it. Don't know for the future. 
Most of the work is done actually .. There are some documentations which is missing, translation of German text and sorting the commands per usage and putting them back in the lists. 
I hope I answered your question.

**Comment by luzpaz** [comment]
I personally am not technically savvy when it comes to the questions you're interested in. We care though, but there is an issue that you maybe not picking up on.

Maybe it's how you're asking the question? You're always in a rush and the pace/rhythm of conversations is very rapid. That comes across as impatient and is not very conducive to collaboration/teamwork.

Here's a characterization just from my perspective:

>HI, I'm interested in direct modeling because I think this is missing in FreeCAD and what will make FreeCAD great! I don't have a lot of time to explain what I'm doing technically oh and also there is a language barrier of a sort. But never mind planning lets just get this working. if you can help that is great. 

All I'm saying is that maybe some of the issues are due to your approach. carlopav offered to have a virtual meeting with you, did that pan out? 

Don't let some folks on the forum get to you too much. Knowing how to collaborate is not simple.

**Comment by MariwanJ** [comment]
If you cannot show up what you CAN .. people don't care of you. Let me do what I am trying to do .. and after that I might be able to open others heart to listen. np.
We have a word in our language, "even if the Cock doesn't yells , sun will rise up and a new day will comes".
Please do what you want to do with the nurbs I worked on .. it is up to you to find a way to present it for the community.

**Comment by luzpaz** [comment]
Thank you for all you work. My heart is open, I just don't understand or know how to help you in your efforts. Yes, it sucks that microelly2's code has been rotting (mainly because it is not very collaboration friendly as you pointed out). It's all so very chaotic and people are unsure how to support.

**Comment by MariwanJ** [comment]
thank you .. hope I can make FreeCAD better and contribute to this project. which I love
